version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/logs:/var/log/postgresql
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
  backend:
    ports:
    - "8111:8000"
    volumes:
        - ./backend:/backend
    build:
      context: backend/
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

