# Generated by Django 3.1.3 on 2020-11-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='background',
            field=models.FilePathField(null=True, path='/backend/blog_crm/blog/static/images'),
        ),
    ]
