# Generated by Django 3.1.3 on 2021-11-25 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_create_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='keywords',
        ),
        migrations.AddField(
            model_name='policy',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), default=list, size=None),
        ),
    ]
