# Generated by Django 3.1.3 on 2021-11-26 17:46

from django.db import migrations, connection
from django.db import backends



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_array_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='keywords',
            new_name='keyword_legacy'
        )
    ]
