# Generated by Django 3.1.3 on 2021-11-26 17:47
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_array_to_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='keywords',
            field=models.ManyToManyField(to='blog.keyword'),
        )
    ]
