# Generated by Django 3.1.3 on 2021-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_migrate_keyword_data_from_array_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
           model_name='policy',
           name='keywords'
        )
    ]
